### ISSUE TITLE
Attach Mobbr lightbox

### ISSUE THREAD

**Issue by patricksavalle** [mobbr/mobbr-browser-plugin#2]
Pressing the button should open the lightbox. 

To see the lightbox, press the button on this URL: https://fastmovingtargets.nl/workforce/547/fast-moving-targets-een-belangrijke-digitale-trend-impact

It should be possible to do this without using AngularJS (the Lightbox is in AngularJS). A webpage can open the lightbox using this javascript:  https://mobbr.com/mobbr-button.js  With some luck the browser-extension can do this too.

The script inserts an iFrame into the page and loads the Lightbox into the iFrame.

@handijk can you check and correct my assumptions?

**Comment by patricksavalle** [comment]
One slight modification needed, was not requested but was kind of implicit and maybe it is easy to add: the lightbox should close when the URL/page changes.

Also it seems pulling does not register any contributor statistics, so if I trigger the pledge no one gets paid. We will be looking into this and fix it. @handijk any thoughts?

**Comment by jrjackso** [comment]
@patricksavalle I wonder if it's because I didn't reference the issue in any commits directly and only referenced it in the pull request comment? (In the past, for smaller single commit changes I referenced the issue number right in the commit comment. That worked I think..)  That said, it does show a "Merged" on that line in the issue thread currently so it should know some code has been pulled in from the participant.

**Comment by patricksavalle** [comment]
Aha! That's it I guess. Looking into it.
